# Configuration for database.
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sense-n-rm
    password: bubbles

